services:
  app:
    image: paxintrade-frontend
    restart: on-failure:5
    volumes:
      - ./.env.production:/app/.env.production
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000/tcp'
