image: node:18

options:
  size: 2x

pipelines:
  # default:
  #   - parallel:
  #       - step:
  #           name: "Build and Test"
  #           caches:
  #             - node
  #           script:
  #             - npm install
  #             - npm run build
  branches:
    release/prod:
      - step:
          name: "Build"
          caches:
            - node
            - ./package-lock.json
            - ./yarn.lock
            - ./node_modules
            - ./.next/cache
          script:
            - npm install
            - git clone https://x-token-auth:$BITBUCKET_ENV_REPO_ACCESS_TOKEN@bitbucket.org/paxintrade/environment-values.git
            - mv environment-values/frontend/.env.production .env
            - rm -rf environment-values
            - npm run build
            - mv public .next/standalone/public
            - mv .next/static .next/standalone/.next/static
            - mv ecosystem.config.js .next/standalone/ecosystem.config.js
          artifacts:
            - .next/standalone/**
      - step:
          name: "Deploy to Production Environment"
          deployment: Production
          script:
            - echo "Deploying to production environment"
            - chmod +x ./deploy_release-prod.sh
            - sudo apt-get update
            - sudo apt-get install rsync
            - ./deploy_release-prod.sh